### PR TITLE
BUGFIX: WA-7093 gdc-agent is making excessive API calls

### PR DESCRIPTION
**Pull request by matejuh**

### CODE REVIEW

**Comment by koles** [comment]
It seems to work but the 2 minutes interval seems to be too conservative to me. How about <10 seconds? What's the interval when you run an ETL task from a local CloudConnect?

**Comment by matejuh** [comment]
I spoke to support and they said me, that execution of graph can take from seconds to hour. So minutes interval seems to me like a good compromise. And I added also a method, where a customer can fine tune the limits... You know better customers use-cases so if you think the shorter limits by default will be better, I can change it. Maybe I can put there the original values and we can notice Nuance that there is a method with fine tuning...

**Comment by koles** [comment]
In general, support is correct but in the short ETL executions are much more frequent which is why I would love to poll as frequently as possible by default. Of course, the default should not be 'excessive'. Can you please work with whoever is the best person for this conversation to find the acceptable minimum?

Thanks a lot and sorry for a delayed response.

**Comment by matejuh** [comment]
No problem. I spoke with support once again and changed the polling function. Maximum poll delay is one minute and before the maximum poll delay is delay prolonged by 1 second after initial 10 seconds delay and start delay. So it waits 10 seconds, then try, then wait 5, 6, 7 ... until 60, 60, 60 seconds... Maximum 15 hours of polling.

**Pull request merged**
